### ISSUE TITLE
Master should not process any tasks when pipelines are running in "ignite" mode

### ISSUE THREAD

**Issue by truehand** [lawrencegripper/nextflowarm#19]
Jumpbox machine should only be used to host the NFS share and to submit new pipeline jobs. In the current setup it's used as an additional worker, too.

**Comment by lawrencegripper** [comment]
Added -cluster.maxCpus 0 to recommended master commands. This ensures none of the tasks are scheduled on the master. 

For example: 

nextflow run nextflow-io/rnatoy -with-docker -process.executor ignite -cluster.join path:/datadisks/disk1/cifs/cluster -with-timeline runtimeline.html -with-trace **-cluster.maxCpus 0**
